### ISSUE TITLE
Permission settings not wholly respected

### ISSUE THREAD

**Issue by pflstr** [FriendsOfFlarum/subscribed#1]
I have to report a bug.

I have set the permission for both, notifications upon a new discussion and notifications upon new users, to admins and mods only. Despite that, both subscription options appear in the user settings of users, that don't belong to one of these groups.

Selecting one of those notifications by users, that don't have the permission to do so, results in a kind of 'half notification' when the selected event happens: In the notification area, the name of the forum as an indicator of a forum wide event is shown as a header in bold, but no further details are revealed.

**Comment by Ralkage** [comment]
Greetings @pflstr,

This has been fixed in the latest version (this issue was the same as #3).

Closing this issue :)
