### ISSUE TITLE
Notification web / email for flagged post

### ISSUE THREAD

**Issue by PeopleInside** [FriendsOfFlarum/subscribed#17]
## Feature Request

**Is your feature request related to a problem? Please describe.**

This extension resolve the issue to report by email when a new post is created or queued for the moderation.
I miss the possibility to be emailed when a post is reported for moderation.

**Describe the solution you'd like**

Add the possibility to be emailed on the case a post is flagged.
Currently there is no way on Flarum to be alerted by email if a post is flagged.

This great extension help to be informed when there is a new post, a new user, a queue for moderation post but not when moderators need take actions on a flagged post for abuse or spam.

**Comment by murdocklawless** [comment]
I installed on flarum 1.2 but no notification came at all condititions.

**Comment by PeopleInside** [comment]
@murdocklawless have you activated notifications in your user settings profile?

**Comment by murdocklawless** [comment]
oh no because there no info about this in description. I activate it and it's ok. thank you very much.
