### ISSUE TITLE
Permission check doesn't work as expected

### ISSUE THREAD

**Issue by jbrgr** [FriendsOfFlarum/subscribed#3]
Hi,

I was wondering why nobody except me gets a notification about created discussions. So tried to find the root cause in the code and the thing is that the permission check referenced below returns true only for my account (I have the admin role, everybody else is just a member).

https://github.com/flagrow/subscribed/blob/8d1a8cfb675cf7f06b6c3611f7852ff5a8e5bd6d/src/Listeners/DiscussionCreated.php#L70

I haven't found the time yet to dig into the permission model and if this an expected behavior for some reason but if I remove the given discussion from the call the check succeeds.

`$recipient->can('viewDiscussions');`

Can you please have a look and tell me if this is the right approach?
If you need more information just let me know.

Thanks

**Comment by Ralkage** [comment]
Greetings @jbrgr ,

This has been fixed in the latest version (this issue was the same as #1).

Closing this issue :)
